try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")

try:
    print:("Hello")
except:
    print("Something went wrong")
else:
    print("Nothing went wrong")